/* tslint:disable */
/* eslint-disable */
/**
 * HLS App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Library {
    'id': string;
    'createdAt': string;
    'updatedAt'?: string;
    'name': string;
    'path': string;
    'type': LibraryTypeEnum;
    'orderIndex'?: number;
}

export const LibraryTypeEnum = {
    Movies: 'MOVIES',
    Tv: 'TV',
    Music: 'MUSIC',
    Anime: 'ANIME',
    Other: 'OTHER'
} as const;

export type LibraryTypeEnum = typeof LibraryTypeEnum[keyof typeof LibraryTypeEnum];


