/* tslint:disable */
/* eslint-disable */
/**
 * HLS App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Media } from './media';

export interface MediaInfo {
    'id': string;
    'createdAt': string;
    'updatedAt'?: string;
    'name': string;
    'type'?: MediaInfoTypeEnum;
    'tagline'?: string;
    'description'?: string;
    'releaseDate'?: string;
    'thumbnail'?: string;
    'banner'?: string;
    'season'?: number;
    'episode'?: number;
    'media'?: Media;
}

export const MediaInfoTypeEnum = {
    Movie: 'MOVIE',
    Tv: 'TV',
    Music: 'MUSIC'
} as const;

export type MediaInfoTypeEnum = typeof MediaInfoTypeEnum[keyof typeof MediaInfoTypeEnum];


