/* tslint:disable */
/* eslint-disable */
/**
 * HLS App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Library } from './library';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaInfo } from './media-info';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaMetadata } from './media-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { TvSeasonCollection } from './tv-season-collection';

export interface Media {
    'id': string;
    'createdAt': string;
    'updatedAt'?: string;
    'path'?: string;
    'library'?: Library;
    'metadata'?: MediaMetadata;
    'info'?: MediaInfo;
    'tvSeason'?: TvSeasonCollection;
}

