/* tslint:disable */
/* eslint-disable */
/**
 * HLS App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Media } from './media';
// May contain unused imports in some cases
// @ts-ignore
import type { TvSeries } from './tv-series';

export interface TvSeason {
    'id': string;
    'createdAt': string;
    'updatedAt'?: string;
    'externalId'?: string;
    'season'?: number;
    'name': string;
    'description'?: string;
    'releaseDate'?: string;
    'thumbnail'?: string;
    'banner'?: string;
    'tvSeries'?: TvSeries;
    'mediaItems'?: Array<Media>;
}

