/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * HlsPlaylistControllerApi - axios parameter creator
 */
export const HlsPlaylistControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateMultiVariantPlaylist: async (mediaId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaId' is not null or undefined
            assertParamExists('generateMultiVariantPlaylist', 'mediaId', mediaId)
            const localVarPath = `/api/playlist/{mediaId}`
                .replace(`{${"mediaId"}}`, encodeURIComponent(String(mediaId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateVodPlaylist: async (mediaId: string, qualityProfile: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaId' is not null or undefined
            assertParamExists('generateVodPlaylist', 'mediaId', mediaId)
            // verify required parameter 'qualityProfile' is not null or undefined
            assertParamExists('generateVodPlaylist', 'qualityProfile', qualityProfile)
            const localVarPath = `/api/playlist/{mediaId}/{qualityProfile}`
                .replace(`{${"mediaId"}}`, encodeURIComponent(String(mediaId)))
                .replace(`{${"qualityProfile"}}`, encodeURIComponent(String(qualityProfile)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HlsPlaylistControllerApi - functional programming interface
 */
export const HlsPlaylistControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HlsPlaylistControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateMultiVariantPlaylist(mediaId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateMultiVariantPlaylist(mediaId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HlsPlaylistControllerApi.generateMultiVariantPlaylist']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateVodPlaylist(mediaId: string, qualityProfile: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateVodPlaylist(mediaId, qualityProfile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HlsPlaylistControllerApi.generateVodPlaylist']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HlsPlaylistControllerApi - factory interface
 */
export const HlsPlaylistControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HlsPlaylistControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateMultiVariantPlaylist(mediaId: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.generateMultiVariantPlaylist(mediaId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateVodPlaylist(mediaId: string, qualityProfile: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.generateVodPlaylist(mediaId, qualityProfile, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HlsPlaylistControllerApi - object-oriented interface
 */
export class HlsPlaylistControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} mediaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public generateMultiVariantPlaylist(mediaId: string, options?: RawAxiosRequestConfig) {
        return HlsPlaylistControllerApiFp(this.configuration).generateMultiVariantPlaylist(mediaId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} mediaId 
     * @param {string} qualityProfile 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public generateVodPlaylist(mediaId: string, qualityProfile: string, options?: RawAxiosRequestConfig) {
        return HlsPlaylistControllerApiFp(this.configuration).generateVodPlaylist(mediaId, qualityProfile, options).then((request) => request(this.axios, this.basePath));
    }
}

