/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * HlsVideoControllerApi - axios parameter creator
 */
export const HlsVideoControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {string} segmentName 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoSegment: async (mediaId: string, qualityProfile: string, segmentName: string, userId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaId' is not null or undefined
            assertParamExists('getVideoSegment', 'mediaId', mediaId)
            // verify required parameter 'qualityProfile' is not null or undefined
            assertParamExists('getVideoSegment', 'qualityProfile', qualityProfile)
            // verify required parameter 'segmentName' is not null or undefined
            assertParamExists('getVideoSegment', 'segmentName', segmentName)
            const localVarPath = `/api/video/{mediaId}/{qualityProfile}/{segmentName}`
                .replace(`{${"mediaId"}}`, encodeURIComponent(String(mediaId)))
                .replace(`{${"qualityProfile"}}`, encodeURIComponent(String(qualityProfile)))
                .replace(`{${"segmentName"}}`, encodeURIComponent(String(segmentName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HlsVideoControllerApi - functional programming interface
 */
export const HlsVideoControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HlsVideoControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {string} segmentName 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVideoSegment(mediaId: string, qualityProfile: string, segmentName: string, userId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVideoSegment(mediaId, qualityProfile, segmentName, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HlsVideoControllerApi.getVideoSegment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HlsVideoControllerApi - factory interface
 */
export const HlsVideoControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HlsVideoControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} mediaId 
         * @param {string} qualityProfile 
         * @param {string} segmentName 
         * @param {string} [userId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoSegment(mediaId: string, qualityProfile: string, segmentName: string, userId?: string, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getVideoSegment(mediaId, qualityProfile, segmentName, userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HlsVideoControllerApi - object-oriented interface
 */
export class HlsVideoControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} mediaId 
     * @param {string} qualityProfile 
     * @param {string} segmentName 
     * @param {string} [userId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getVideoSegment(mediaId: string, qualityProfile: string, segmentName: string, userId?: string, options?: RawAxiosRequestConfig) {
        return HlsVideoControllerApiFp(this.configuration).getVideoSegment(mediaId, qualityProfile, segmentName, userId, options).then((request) => request(this.axios, this.basePath));
    }
}

